### ISSUE TITLE
No option of Capturing multiple images to generate a PDF.

### ISSUE THREAD

**Issue by neelmehta14** [dynamsoft-rd-0/dbrjs-mass-samples#1]
Hello,
Firstly, 
After the barcode getting scanned, the barcode reader is not getting closed. It keeps on scanning.
Secondly,
There is no option for capturing multiple images. I need to have a functionality in which I will be having a hard copy document to be scanned and uploaded to Salesforce which can be of 5-6 pages.
Please guide here.

**Comment by neelmehta14** [comment]
https://user-images.githubusercontent.com/24801764/129357419-d717c3ce-c9d5-4747-8b98-a28cf9157fb9.mp4

Please find the screen recording for the issue

**Comment by Keillion** [comment]
Hi @neelmehta14 , sorry for not having time to read all your email communication with Misha.

The [salesforce-dbr-dwt-pdf.vfp](https://github.com/dynamsoft-rd-0/dbrjs-mass-samples/blob/master/salesforce-dbr-dwt-pdf/salesforce-dbr-dwt-pdf.vfp) do the follow things:

1. Scan 3 barcodes, which will filter out the same barcode in a 3s by default. (line 23)
2. After 3 barcodes is done, hide the scanner. (line 27)
3. Each time a barcode is scanned, the related frame will save as a canvas. (line 22 and line 25)
4. The `generate pdf` send 3 canvases into dwt. (line 52). 
5. Then dwt generate a blob of pdf, which contains the 3 frames. (line 66)
6. The blob of pdf is logged into console. The uploading process you need to do yourself.

Does `a hard copy document` mean you want:
1. scan a image 
2. read barcode in the image
3. loop some times
4. generate a pdf of all those images

I make a new one tomorrow. The key api is `scanner.singleFrameMode = true` before `show`.

**Comment by neelmehta14** [comment]
Hi @Keillion,
Let me explain the functionality which we are looking for.
The name of the Application is POD(Proof of Delivery).
It will be used in Mobiles within Salesforce mobile app by a non technical person(Delivery Guy).
Steps  : 
	1) The delivery guy will Scan a barcode of the customer.
	2) On scanning the barcode, the  barcode scanner will be turned off and the result of barcode will be saved in a textbox.
	3) Then the customer will provide a Physical Hard Copy of a document (There will be no barcodes inside it and no scanning of barcode is required here).
	4) The delivery guy will capture every page of the document. A pdf should be generated consisting of the captured images. 
	5) Upload that PDF file to Salesforce custom object (the key for uploading the PDF to a particular record of the Salesforce object will be the result of the barcode)
	
	Eg: Delivery guy scans a barcode of the customer and the result of scanning appears in the textbox. Let us assume that after scanning the barcode, the resultant number set in the textbox is 'CA-1234567890'.
	This  'CA-1234567890' will be the key of the Salesforce record in which the PDF has to be uploaded.
	
I hope you are clear with the functionality. Please let me know if you have any questions.
Also, this matter has taken a lot of time of the client and he is in a big hurry now. Please provide the perfect solution to the earliest and let us close the matter.

Thanks & Regards,
Neel Mehta
+918140000914

**Comment by Keillion** [comment]
New [salesforce-dbr-dwt-pdf-2.vfp](https://github.com/dynamsoft-rd-0/dbrjs-mass-samples/blob/master/salesforce-dbr-dwt-pdf/salesforce-dbr-dwt-pdf-2.vfp)

Works but not prefect.

I am not familiar with some dwt apis, so i'll ask someone for help and update it in Monday.

Hope it helps. @neelmehta14

**Comment by neelmehta14** [comment]
The given code has input type as files. But we do not want that. Just like the barcode reader, there should be a CAMERA opened which will be having a 'Capture' button. The delivery guy will take multiple images from the camera (One by One) and after that a pdf should be generated of all the images captured and that pdf has to be uploaded to Salesforce.

**Comment by Keillion** [comment]
> 
> 
> The given code has input type as files. But we do not want that. Just like the barcode reader, there should be a CAMERA opened which will be having a 'Capture' button. The delivery guy will take multiple images from the camera (One by One) and after that a pdf should be generated of all the images captured and that pdf has to be uploaded to Salesforce.

I have written in line 30: `todo: use dwt's camera api, so one can take multiple pics continuously` So pls wait patiently until Monday.

line 4: `capture="camera"`  In mobile, it opens a native camera. In PC it open explorer.

`that pdf has to be uploaded to Salesforce`: Sorry, I'll not do that. I'm unfamiliar with Salesforce upload API. This seems to be beyond our support.

**Comment by neelmehta14** [comment]
Hi @Keillion
Ofcourse the Salesforce upload will be handled from my side. You just need to handle the barcode reader and camera capture and generating pdf. 
I will be waiting for the solution on Monday. Thanks!

**Comment by Keillion** [comment]
@neelmehta14 
Finnally~ done.

**Comment by neelmehta14** [comment]
Hi @Keillion 
Thanks a lot man for the solution. I just have one last question.
Can you guide me how do I use the pdf that is generated.
I want to pass that PDF to my Apex class from JavaScript and I am not able to perform that.
Also, is the pdf, which is declared as 'let pdf=await ...... ' a BLOB or String?
Can you please help here.

**Comment by Keillion** [comment]
@neelmehta14 
The `pdf` is a `blob`. I really don't know `apex` too much, as well as other team members.

We will try to learn, but do not keep too much hope😂.

**Comment by neelmehta14** [comment]
It is perfectly fine @Keillion. Thanks for the help. Cheers!
